// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZOMrYruOzwVhiZKK_pADTkbU6tIc62o',
    appId: '1:1056262170284:web:38ad45fdba5d01adba2109',
    messagingSenderId: '1056262170284',
    projectId: 'wall-tutorial-3b425',
    authDomain: 'wall-tutorial-3b425.firebaseapp.com',
    storageBucket: 'wall-tutorial-3b425.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnzfYuDaKM6pbox1ivHAzMUMn96EmW5no',
    appId: '1:1056262170284:android:54e810e8d074fd25ba2109',
    messagingSenderId: '1056262170284',
    projectId: 'wall-tutorial-3b425',
    storageBucket: 'wall-tutorial-3b425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtx_ECr6X5Q89EBjE2PHnklDV1t_6uopY',
    appId: '1:1056262170284:ios:017bdca9a7c22b75ba2109',
    messagingSenderId: '1056262170284',
    projectId: 'wall-tutorial-3b425',
    storageBucket: 'wall-tutorial-3b425.appspot.com',
    iosBundleId: 'com.example.socialMediaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtx_ECr6X5Q89EBjE2PHnklDV1t_6uopY',
    appId: '1:1056262170284:ios:4f2defbe2206a695ba2109',
    messagingSenderId: '1056262170284',
    projectId: 'wall-tutorial-3b425',
    storageBucket: 'wall-tutorial-3b425.appspot.com',
    iosBundleId: 'com.example.socialMediaFirebase.RunnerTests',
  );
}
